# Generated by Django 3.0.3 on 2020-03-24 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0002_auto_20200320_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hash_val',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
