# Generated by Django 3.0.3 on 2020-03-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0003_course_hash_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hash_val',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
